### ISSUE TITLE
When will you release the Character Level Mask?

### ISSUE THREAD

**Issue by gyzz** [cs-chan/Total-Text-Dataset#1]
Hi, when will you release the Character Level Mask?

**Comment by ckchng** [comment]
Hi there, we are currently cleaning the character level mask, targeting to complete by the end of March, stay tune.

**Comment by gyzz** [comment]
ok, thank you for your reply.

**Comment by ckchng** [comment]
Hi,

The character level mask is now available.

**Comment by gyzz** [comment]
OK, Thank you for informing me.

**Comment by vince2003** [comment]
Hello,
How can I download the character level mask?
Thank you!
