### ISSUE TITLE
why do detection_filtering in the Deteval.py

### ISSUE THREAD

**Issue by xiliu** [cs-chan/Total-Text-Dataset#11]
1,why do detection_filtering in the [Deteval.py ](https://github.com/cs-chan/Total-Text-Dataset/blob/9ed8b6ad0475e235b26849bfb47a7943265132c7/Evaluation_Protocol/Python_scripts/Deteval.py#L86)
2,why delete [groundtruths](https://github.com/cs-chan/Total-Text-Dataset/blob/9ed8b6ad0475e235b26849bfb47a7943265132c7/Evaluation_Protocol/Python_scripts/Deteval.py#L88) which label is '#'

**Comment by ckchng** [comment]
Hi there,

It's to remove 'do not care' text region (which usually are languages that the dataset doesn't consider, illegible text regions, etc.). According to the standard protocol (like ICDAR2015 and COCO-Text), these text regions are not supposed to contribute to the evaluation.

**Comment by xiliu** [comment]
Thank you for replying, i get it.
