### ISSUE TITLE
Confusion in input directory in Python Scripts

### ISSUE THREAD

**Issue by sv2812** [cs-chan/Total-Text-Dataset#12]
Hi , 
What is the detection text file that we are including in input_dir in Python Scripts ?

**Comment by ckchng** [comment]
Hi there,

It should include the detection output (text file format) of your model. Inside the text file it should be stored in format below.

'img_1.txt'
y0,x0, y1,x1, ...... yn, xn
y0,x0, y1,x1, ...... yn, xn
y0,x0, y1,x1, ...... yn, xn

**Comment by sv2812** [comment]
Oh alright . I'll try that . Thanks !
