### ISSUE TITLE
about DetEval.py evaluation speed boosting.

### ISSUE THREAD

**Issue by princevandev** [cs-chan/Total-Text-Dataset#16]
Hi, I found that the evaluation in this code run extremely slowly and most time-consuming operation in your code is area/area_of_intersection/iou. These functions are based on mask counting, which depends highly on the size of images(some big-size images can be bottleck of computing). 
I have replaced mask counting operation with polygon coordinate computing(which uses shapely, a geometry lib written in python) so that it highly boosts the evaluatoin process.  
Can I make a PR? Hope for your replying, thx.

**Comment by ckchng** [comment]
Oh yes you are most welcome, thanks for wanting to contribute! And I assume that you have already tested out your code? In particular, does the library provides an exact solution instead of approximation when it comes to calculating the area of intersection?

**Comment by princevandev** [comment]
I have compared the result of mask counting method and polygon based method, their result have a bit difference(1 to 3 pixels in computing iou between 2 polygons with area about 10000 pixels) because mask counting based implement discretize the coordinates to pixels. In fact, I think the polygon based method produce more precise result.

**Comment by ckchng** [comment]
Yup that makes sense. Also, less than 1 percent of differences is probably negligible in practice.

**Comment by princevandev** [comment]
Thx for your replying, I will make a pull request soon! 😆
