### ISSUE TITLE
The result of end-to-end recognition.

### ISSUE THREAD

**Issue by MhLiao** [cs-chan/Total-Text-Dataset#23]
@cs-chan It seems that there is a mistake in the result of end-to-end recognition. 
In the Neurocomputing2019 paper, the authors say that "Total-Text [33] contains 744 horizontal text images for testing", which means that they did not evaluate the curved samples. Moreover, it is only a text recognition method which does not involve detection, instead of an end-to-end recognition method which involves both detection and recognition.

**Comment by cs-chan** [comment]
Thank you for your information. We have checked and confirmed it. In this case, we have removed the paper in the table to avoid confusion.
