### ISSUE TITLE
about original download 

### ISSUE THREAD

**Issue by simplify23** [cs-chan/Total-Text-Dataset#26]
hello,i can not open the original total-text dataset of the Google drivers' download link . Is there a download  link of baidu cloud? thanks

**Comment by chunchet-ng** [comment]
Hi there,

Thank you for your interest in Total Text.

The download link of Baidu Yun is as follows:
https://pan.baidu.com/s/1-vyfEsjHuw89EXKxRLmVMA 
Password: 5byk
