### ISSUE TITLE
Issue with gt_reading_mod with newest groundtruth datasets

### ISSUE THREAD

**Issue by mandytoh1212** [cs-chan/Total-Text-Dataset#28]
With the newest ground truth labels, should gt_reading_mod now look like this? I couldn't ge thte evaluation script to run with the existing version

```
def gt_reading_mod(gt_dir, gt_id):
    gt_id = gt_id.split('.')[0]
    gt = io.loadmat('%s/gt_%s.mat' % (gt_dir, gt_id))
    gt = `gt['gt']`
    return gt
```

**Comment by ckchng** [comment]
Hi there sorry for getting back so late. Have you manage to solve this problem? There is no new version of test set ground truth so the code should remain the same.

**Comment by ckchng** [comment]
I'm closing this for now.
