### ISSUE TITLE
Confusion about detection leaderboard

### ISSUE THREAD

**Issue by shine-lcy** [cs-chan/Total-Text-Dataset#29]
Algorithms in detection leaderboard include both detection-only and E2E methods.
Under the same detection framework, E2E training will bring improved detection performance. I think it's somewhat unfair to algorithms that only target detection task.
It is difficult for researchers who only focus on  detection task to efficiently obtain information from the table to compare their own algorithms.
Maybe my opinion is shallow. Hope to get your reply.

**Comment by cs-chan** [comment]
Hi @shine-lcy  thank you for your valuable comments. As an improvement to the detection leaderboard, we have highlighted those E2E-based methods in italic font and a hash in front of the method.
