### ISSUE TITLE
CUTE80

### ISSUE THREAD

**Issue by wushilian** [cs-chan/Total-Text-Dataset#3]
Hi,I have a question about CUTE80 dataset,in GroundTruth.xml ,there are 147 imgs,but in fact there are only 80 imgs.I crop from 80 imgs and get 202 cropped images,but it seems like should have 288 cropped images,So could you provide me an right CUTE80 dataset?

**Comment by cs-chan** [comment]
Thanks for your comments. Let me check and come back to you.

**Comment by jiaying96** [comment]
@wushilian can you  share  288 cropped images?
