### ISSUE TITLE
There is a word mistake...

### ISSUE THREAD

**Issue by bboyHB** [cs-chan/Total-Text-Dataset#31]
In the file **poly_gt_img149.txt** of [groundtruth](https://drive.google.com/file/d/1v-pd-74EkZ3dWe6k0qppRtetjdPQ3ms1/view?usp=sharing), the transcription should be 'SNACK' but got 'SNAKC' in line 3.

**Comment by cs-chan** [comment]
Thank you very much. We will rectify it.
