### ISSUE TITLE
TotalText annotation

### ISSUE THREAD

**Issue by yustiks** [cs-chan/Total-Text-Dataset#33]
Hello!
I try to understand format of input file.
Can you please explain what every field in the following format means?
{"image_id": 8, 
"bbox": [551.0, 193.0, 38.0, 25.0], 
"area": 950.0, 
"rec": [18, 16, 16, 24, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96], 
"category_id": 1, 
"iscrowd": 0, 
"id": 40, 
"bezier_pts": [552.0, 193.0, 565.33, 191.33, 577.33, 194.33, 588.0, 202.0, 581.0, 217.0, 571.0, 213.67, 561.0, 210.33, 551.0, 207.0]},

**Comment by chunchet-ng** [comment]
Hi there,

Sorry for the late reply.

I believe that the format above is taken from the AdelaiDet detection repo, which you have already opened an [issue ](https://github.com/aim-uofa/AdelaiDet/issues/227) about it. 

You can find the definition of original TotalText annotations [here](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text).

Thank you.
