### ISSUE TITLE
where can i  load  the images and labels data

### ISSUE THREAD

**Issue by cqray1990** [cs-chan/Total-Text-Dataset#37]

**Comment by chunchet-ng** [comment]
Hi there,

I m not sure what you mean by loading exactly.

But you can get the images [here ](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Dataset) and the annotations [here](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text).

Feel free to reopen the issue if you still have any questions.

Thanks.
