### ISSUE TITLE
Generating ground truth of text

### ISSUE THREAD

**Issue by Didier0** [cs-chan/Total-Text-Dataset#38]
Hi, can you tell me how do you generate file with ground truth of text instance on image?

**Comment by chunchet-ng** [comment]
Hi there, do you want to draw ground-truth bounding boxes on the image? 

If yes, then you can use Pillow's ImageDraw.polygon or ImageDraw.rectangle for this task.

**Comment by Didier0** [comment]
I have image with text instances on it and now I need to generate a file which consist ground truth of text instance that is on image. 

Something like this, I need ground truth position of text instances, of bounding box. 
![image](https://user-images.githubusercontent.com/95293282/166698735-a5176042-d52c-4e5f-86a7-ca9591ac2898.png)

**Comment by chunchet-ng** [comment]
You can get ground-truth bounding boxes at [this page](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text).

**Comment by Didier0** [comment]
Thank you :)

**Comment by chunchet-ng** [comment]
You are welcome! 😄
