### ISSUE TITLE
Misunderstanding the scripts 

### ISSUE THREAD

**Issue by Didier0** [cs-chan/Total-Text-Dataset#39]
Hi, can you explain me some scripts?

What is difference between: T3 annotation tool scripts, `Detection_Recognition_Annotation_script.m` and the python scripts in `Evaluation_Protocol`? 

Some script is used for generating file with groud truth of text on image (T3 ?), one is used for drawing polygon bounding box (`Detection_Recognition_Annotation_script.m`?) and the main script where magic is happening is `Deteval.py` or `Pascal_VOC.py` ?

**Comment by chunchet-ng** [comment]
HI there,

I think you are misunderstanding the purpose of these scripts. Files in the [Annotation Tool folder](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Annotation_tools) are meant for the annotation platform we used to annotate TotalText, while the [Evaluation Protocol folder](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Evaluation_Protocol) has necessary scripts to evaluate the prediction results from a model.

If you want to draw polygons on the image, you need to write your own code to handle:

1. Reads in TotalText ground-truth polygons and image
2. Draw on the image using Pillow or OpenCV

Do note that we do not provide such code in this repo.

**Comment by Didier0** [comment]
Ok, thank you for explanation!
