### ISSUE TITLE
Where is the statement for the annotation format.

### ISSUE THREAD

**Issue by zxDeepDiver** [cs-chan/Total-Text-Dataset#4]
Hi, thank you so much for providing such a novel dataset. 

I want to do some experiments on it, but I cann't find any explanation for the annotation format and the submission format for evaluation (the meaning each element of the gt stands for). 

Could you  please help me find that?

**Comment by ckchng** [comment]
Hi there, thank you for your interest in our dataset. The format is actually here. 
https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text 

All the best in your exploration!

**Comment by smartcatdog** [comment]
> https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text

thanks for your sharing,
however, there is no format meanings about file which ends with .mat,
such as poly_gt_img1.mat, link is
[https://github.com/cs-chan/Total-Text-Dataset/blob/master/Evaluation_Protocol/Examples/Groundtruth/poly_gt_img1.mat](url)
thanks for your apply~
