### ISSUE TITLE
请问这两种方式有何不同，是否得到相差较多的检测结果？

### ISSUE THREAD

**Issue by huahuabai** [cs-chan/Total-Text-Dataset#40]
请问这两种方式有何不同，是否得到相差较多的检测结果？
盼复，感谢您！

![image](https://user-images.githubusercontent.com/55180640/171544189-e9bfde49-024e-474d-a666-b9999090055f.png)

**Comment by chunchet-ng** [comment]
Hi there,

The differences between these two versions are as follows:

1. Mask counting version is using skimage's polygon class, while another version is using shapely's.
2. The later version has a faster speed, which was introduced by this [pull request](https://github.com/cs-chan/Total-Text-Dataset/pull/17).

Theoretically, they should return the same results. We recommend you use the later version as it is more up-to-date.

Thank you.
