### ISSUE TITLE
How to bound text region with polygons after connected component analysis

### ISSUE THREAD

**Issue by xieenze** [cs-chan/Total-Text-Dataset#5]
Hello, I am confused about some details. In your paper you first do segmentation on image, then binarize the saliency map and do connected component analysis. However, I don't know how to bound them tightly with polygons?  Can you share some details?

**Comment by ckchng** [comment]
Sure. First of all, you get pixel map as the output from the Deconvnet. 
1) We use the Matlab function 'bwconncomp' to get the CC.
2) Then use the Matlab function 'regionprops' to retrieve the 'Convexhull', which is all the polygon vertices of every CCs.
