### ISSUE TITLE
Don't know how to evaluate by Python

### ISSUE THREAD

**Issue by xieenze** [cs-chan/Total-Text-Dataset#6]
I see there is an example floder in Evaluation_Protocol, but in Python_scripts, I don't know where you read them.  Can you give us some simple examples about how to evaluate by Python?  
Thank you very much.

**Comment by ckchng** [comment]
The first three lines of the python script is for you to set the necessary directories.

As I've listed in the comment:
'input_dir' is where you keep your detection text files.
'gt_dir' is where you keep the ground-truths (provided by us).
'fid_path' can be any place you want it to be. It contains per image result.

Your detection file should have the name of 'img(id).txt'. For instance, img1.txt.
The output should be stored in the form of 'y0,x0,y1,x1, .... yn,xn'

Let me know if this is clear enough for you.

**Comment by xieenze** [comment]
Thanks, now I know it.
