### ISSUE TITLE
How to parse the annotation file?

### ISSUE THREAD

**Issue by vinayakarannil** [cs-chan/Total-Text-Dataset#7]
Do you have any script how to parse the Polygon ground truth file?

**Comment by ckchng** [comment]
No we don't have any specific script but the format (both .txt and .mat) are clearly written under the groundtruth folder. It should be pretty easy to be parsed into your desired format. Do let us know if you  need further assistance.

**Comment by vinayakarannil** [comment]
Thank you for replying. I am struggling to parse the files as it is not in any standard formats like json or xml.  I think i will have to use some regex to parse the files

**Comment by ckchng** [comment]
If you happened to use Python or Matlab for your application, you can refer to the scripts below on how to parse our annotation. Hope it helps!

Python - https://github.com/cs-chan/Total-Text-Dataset/tree/master/Evaluation_Protocol/Python_scripts 
Matlab - https://github.com/cs-chan/Total-Text-Dataset/tree/master/Evaluation_Protocol

**Comment by smartcatdog** [comment]
> but the format

thanks for your sharing,
and i want to ask what is the meaning of the number of the mat format file, 
such as 
[https://github.com/cs-chan/Total-Text-Dataset/blob/master/Evaluation_Protocol/Examples/Groundtruth/poly_gt_img1.mat](url)

**Comment by smartcatdog** [comment]
> No we don't have any specific script but the format (both .txt and .mat) are clearly written under the groundtruth folder. It should be pretty easy to be parsed into your desired format. Do let us know if you need further assistance.

thanks for your sharing,
and i want to ask what is the meaning of the number of the mat format file,
such as
[https://github.com/cs-chan/Total-Text-Dataset/blob/master/Evaluation_Protocol/Examples/Groundtruth/poly_gt_img1.mat](url)
