### ISSUE TITLE
Miss orientation label for some annotations

### ISSUE THREAD

**Issue by billqxg** [cs-chan/Total-Text-Dataset#8]
eg:
img958.jpg [array(['x:'], dtype='<U2')
 array([[125, 162, 191, 191, 157, 119]], dtype=int16)
 array(['y:'], dtype='<U2')
 array([[627, 631, 626, 637, 639, 636]], dtype=int16)
 array(['DIENST'], dtype='<U6') array([], dtype='<U1')]

**Comment by ckchng** [comment]
Thanks for the notification. We will update it in the next patch!

**Comment by ckchng** [comment]
Attached along the patch to amend the mistake mentioned above. 

[gt_correction_patch.zip](https://github.com/cs-chan/Total-Text-Dataset/files/2574553/gt_correction_patch.zip)
