### ISSUE TITLE
rules for annotation

### ISSUE THREAD

**Issue by ran337287** [cs-chan/Total-Text-Dataset#9]
I have some question about rules of annotation. 
As for curved text, why do you assign them different number of coordinates? What's the maximum number?

**Comment by ckchng** [comment]
Hi,

The annotation was done with the mindset of binding the text regions as tight as possible with the least amount of polygon vertex. Some of the curved texts are more curved than the others hence require more vertex. We didn't keep track of the vertex count, but a simple script could do the trick.  Hope that helps, good day!

**Comment by ran337287** [comment]
Hi，
Thanks very much!
I haved test functions ispolycw and poly2cw in matlab, but I am confused by these two function.
For example, x=[0, 4, 4, 0], y=[0, 0, 4, 4], these four vertices are in clockwise order and ispolycw returns 0, poly2cw returns [0,4,4,0] [4,4,0,0]; whether x in this function is vertical pixels' coordinates in image? If it is, x in evaluation means the opposite.
And change x,y to [4,0,0,4] [4,0,4,0], ispolycw returns 1 poly2cw can not return order  correctly.

**Comment by ckchng** [comment]
Hi there,

As for your first question, where x=[0, 4, 4, 0], y=[0, 0, 4, 4], I don't see a problem with the result that you are getting. It is indeed a counter-clockwise polygon, and poly2cw did change the order for you.

As for your 2nd question, you provided a self-intersecting polygon into poly2cw, which is probably not supported by the function. See this --> http://compgroups.net/comp.soft-sys.matlab/poly2cw-what-happened-to-it/881428.

**Comment by ran337287** [comment]
Hi, Thank you very much.
so the x, y in ispolycw correspond to height, width respectively in image， that is to mean direction in polycw is opposite to direction in image. As for image, vertices will be reordered to a counter-clockwise squence.
By the way, these two squence (clockwise or counter clockwise) will not have any effect on computing area.
